
services:
  springboot-app:
    build: .
    container_name: springboot-app
    ports:
      - "8090:8090"
    depends_on:
      - postgres-db
      - redis-cache
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/BBIL_Alarm_DB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATA_REDIS_HOST: redis-cache
      SPRING_DATA_REDIS_PORT: 6379
    networks:
      - app-network

  nextjs-app:
    build:
     context: ./../AlarmDashBoardReactApp
     args:
       NEXT_PUBLIC_API_URL: http://host.docker.internal:8090
    container_name: nextjs-app
    
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://host.docker.internal:8090
    depends_on:
      - springboot-app
    networks:
      - app-network
    extra_hosts: 
      - "host.docker.internal:host-gateway"

  postgres-db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: BBIL_Alarm_DB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis-cache:
    image: redis:7
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: